apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deployment-1
spec:
  selector:
    matchLabels:
      app: spring-app
  replicas: 2
  strategy:
    type: Recreate
  template: 
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: yaniv
        image: yanivomc:spring-music
        ports:
        - containerPort: 8080
---- 

apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer