apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deployment-1
spec:
  selector:
    matchLabels:
      app: spring-app
  replicas: 2
  strategy:
    type: Recreate
  template: 
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: yaniv
        image: yanivomc/spring-music:latest
        ports:
        - containerPort: 8080
